{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\"} |= ``"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", bar_label=\"DELETE\"}[$__rate_interval])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "request_total{bar_label=\"GET\", source=\"jwt-pizza-service\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "request_total{bar_label=\"POST\", source=\"jwt-pizza-service\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "request_total{bar_label=\"PUT\", source=\"jwt-pizza-service\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "request_total{source=\"jwt-pizza-service\", bar_label=\"ALL\"}",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "latency_factoryLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "pizza_factory_latency"
    },
    {
     "expr": "latency_serviceLatency{source=\"jwt-pizza-service\"}",
     "legendFormat": "pizza_service_latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purchase_revenue{source=\"jwt-pizza-service\"}",
     "legendFormat": "revenue"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(AuthAttempts_success{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "successful_Auth_Attempts"
    },
    {
     "expr": "rate(AuthAttempts_rate{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Failed_Auth_Attempts"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memoryUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory_Usage"
    },
    {
     "expr": "system_cpuUsage{source=\"jwt-pizza-service\"}",
     "legendFormat": "cpu_Usage"
    }
   ]
  },
  {
   "title": "ActiveUsers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "ActiveUsers_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active_Users"
    }
   ]
  },
  {
   "title": "Pizza Purchasing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(purchase_PizzaPurchases{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "pizzas_Purchased"
    },
    {
     "expr": "rate(purchase_purchaseFailures{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "pizzas_Failed"
    }
   ]
  }
 ]
}